[2025-06-30T10:40:43.581+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_kpi_daily_batch.run_batch_youtube_etl manual__2025-06-30T10:40:42.915785+00:00 [queued]>
[2025-06-30T10:40:43.585+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_kpi_daily_batch.run_batch_youtube_etl manual__2025-06-30T10:40:42.915785+00:00 [queued]>
[2025-06-30T10:40:43.586+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-06-30T10:40:43.671+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): run_batch_youtube_etl> on 2025-06-30 10:40:42.915785+00:00
[2025-06-30T10:40:43.675+0000] {standard_task_runner.py:60} INFO - Started process 232 to run task
[2025-06-30T10:40:43.677+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'youtube_kpi_daily_batch', 'run_batch_youtube_etl', 'manual__2025-06-30T10:40:42.915785+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/youtube_etl_dag.py', '--cfg-path', '/tmp/tmp27unpk06']
[2025-06-30T10:40:43.680+0000] {standard_task_runner.py:88} INFO - Job 18: Subtask run_batch_youtube_etl
[2025-06-30T10:40:43.691+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.9/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-30T10:40:43.708+0000] {task_command.py:423} INFO - Running <TaskInstance: youtube_kpi_daily_batch.run_batch_youtube_etl manual__2025-06-30T10:40:42.915785+00:00 [running]> on host f52b64ea71aa
[2025-06-30T10:40:43.744+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='yonatan' AIRFLOW_CTX_DAG_ID='youtube_kpi_daily_batch' AIRFLOW_CTX_TASK_ID='run_batch_youtube_etl' AIRFLOW_CTX_EXECUTION_DATE='2025-06-30T10:40:42.915785+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-30T10:40:42.915785+00:00'
[2025-06-30T10:40:43.754+0000] {logging_mixin.py:188} INFO - Running ETL for channel: UCvtRTOMP2TqYqu51xNrqAzg
[2025-06-30T10:40:44.622+0000] {logging_mixin.py:188} INFO - [load_to_postgres] Error: relation "youtube_kpi.youtube_channel_stats" does not exist
LINE 2:             INSERT INTO youtube_kpi.youtube_channel_stats (
                                ^
[2025-06-30T10:40:44.622+0000] {logging_mixin.py:188} INFO - Successfully processed channel: Brawadis (UCvtRTOMP2TqYqu51xNrqAzg)
[2025-06-30T10:40:44.623+0000] {logging_mixin.py:188} INFO - Running ETL for channel: UC0ZV6M2THA81QT9hrVWJG3A
[2025-06-30T10:40:45.613+0000] {logging_mixin.py:188} INFO - [load_to_postgres] Error: relation "youtube_kpi.youtube_channel_stats" does not exist
LINE 2:             INSERT INTO youtube_kpi.youtube_channel_stats (
                                ^
[2025-06-30T10:40:45.613+0000] {logging_mixin.py:188} INFO - Successfully processed channel: Apex Legends (UC0ZV6M2THA81QT9hrVWJG3A)
[2025-06-30T10:40:45.614+0000] {logging_mixin.py:188} INFO - Running ETL for channel: UCYzPXprvl5Y-Sf0g4vX-m6g
[2025-06-30T10:40:46.479+0000] {logging_mixin.py:188} INFO - [load_to_postgres] Error: relation "youtube_kpi.youtube_channel_stats" does not exist
LINE 2:             INSERT INTO youtube_kpi.youtube_channel_stats (
                                ^
[2025-06-30T10:40:46.480+0000] {logging_mixin.py:188} INFO - Successfully processed channel: jacksepticeye (UCYzPXprvl5Y-Sf0g4vX-m6g)
[2025-06-30T10:40:46.480+0000] {logging_mixin.py:188} INFO - Running ETL for channel: UCbg_UMjlHJg_19SZckaKajg
[2025-06-30T10:40:47.376+0000] {logging_mixin.py:188} INFO - [load_to_postgres] Error: relation "youtube_kpi.youtube_channel_stats" does not exist
LINE 2:             INSERT INTO youtube_kpi.youtube_channel_stats (
                                ^
[2025-06-30T10:40:47.376+0000] {logging_mixin.py:188} INFO - Successfully processed channel: XXL (UCbg_UMjlHJg_19SZckaKajg)
[2025-06-30T10:40:47.377+0000] {logging_mixin.py:188} INFO - Running ETL for channel: UCDVPcEbVLQgLZX0Rt6jo34A
[2025-06-30T10:40:48.299+0000] {logging_mixin.py:188} INFO - [load_to_postgres] Error: relation "youtube_kpi.youtube_channel_stats" does not exist
LINE 2:             INSERT INTO youtube_kpi.youtube_channel_stats (
                                ^
[2025-06-30T10:40:48.299+0000] {logging_mixin.py:188} INFO - Successfully processed channel: Mr. Kate (UCDVPcEbVLQgLZX0Rt6jo34A)
[2025-06-30T10:40:48.299+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-06-30T10:40:48.307+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=youtube_kpi_daily_batch, task_id=run_batch_youtube_etl, execution_date=20250630T104042, start_date=20250630T104043, end_date=20250630T104048
[2025-06-30T10:40:48.352+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-30T10:40:48.365+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
